yc:
  bucket:
    images: label-studio-import-images
    tasks: label-studio-import-tasks-2
    title_tasks: label-studio-import-title-tasks
    annotations_summary: annotations-summary
    annotations: label-studio-export-annotations
  aws_access_key_id: <SET ME>
  aws_secret_access_key: <SET ME>

yandex_disk:
  download_url: https://cloud-api.yandex.net/v1/disk/public/resources/download
  # https://yandex.com/dev/direct/doc/start/token.html
  token: <SET ME>


