google_api_key: <SET ME>

yandex:
  disk:
    oauth_token: <SET ME>
  cloud:
    aws_access_key_id: <SET ME>
    aws_secret_access_key: <SET ME>
    bucket:
      document: ttdoc
      metadata: ttmeta
      content: ttcontent