"""create documents table

Revision ID: cd919af6109f
Revises: 
Create Date: 2025-10-22 12:39:13.540854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd919af6109f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('md5', sa.String(), nullable=False, primary_key=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('ya_path', sa.String(), nullable=True),
    sa.Column('ya_public_url', sa.String(), nullable=True),
    sa.Column('ya_public_key', sa.String(), nullable=True),
    sa.Column('ya_resource_id', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('publish_date', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('translated', sa.Boolean(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('content_extraction_method', sa.String(), nullable=True),
    sa.Column('metadata_extraction_method', sa.String(), nullable=True),
    sa.Column('full', sa.Boolean(), nullable=True),
    sa.Column('sharing_restricted', sa.Boolean(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('content_url', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('upstream_metadata_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('md5')
    )
    op.create_index(op.f('ix_document_md5'), 'document', ['md5'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_md5'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
