name: Calculate words count in monocorpus datasets

on:
  workflow_dispatch:  # Manually triggered workflow

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4.1.4
        - uses: actions/setup-python@v5.1.0
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Count words in datasets
          run: python src_old/main.py wc >> $GITHUB_STEP_SUMMARY