"""Prompt modules for content and metadata extraction."""

from .content import (
    EXTRACT_CONTENT_PROMPT_FOOTNOTE_PART,
    EXTRACT_CONTENT_PROMPT_NO_TITLE,
    EXTRACT_CONTENT_PROMPT_POSSIBLE_TITLE,
    EXTRACT_CONTENT_PROMPT_PRELUDE,
    EXTRACT_CONTENT_PROMPT_STATIC_BODY,
    cook_extraction_prompt,
)
from .metadata import (
    DEFINE_META_PROMPT_BODY,
    DEFINE_META_PROMPT_CRH_FOOTER,
    DEFINE_META_PROMPT_NON_PDF_HEADER,
    DEFINE_META_PROMPT_PDF_HEADER,
    DEFINE_META_PROMPT_TT_FOOTER,
)
from .metadata_evaluation import build_library_applicability_prompt

__all__ = [
    "EXTRACT_CONTENT_PROMPT_PRELUDE",
    "EXTRACT_CONTENT_PROMPT_STATIC_BODY",
    "EXTRACT_CONTENT_PROMPT_FOOTNOTE_PART",
    "EXTRACT_CONTENT_PROMPT_POSSIBLE_TITLE",
    "EXTRACT_CONTENT_PROMPT_NO_TITLE",
    "DEFINE_META_PROMPT_PDF_HEADER",
    "DEFINE_META_PROMPT_NON_PDF_HEADER",
    "DEFINE_META_PROMPT_BODY",
    "DEFINE_META_PROMPT_TT_FOOTER",
    "DEFINE_META_PROMPT_CRH_FOOTER",
    "build_library_applicability_prompt",
    "cook_extraction_prompt",
]
